#!/bin/bash
### BY GOD OF SKY ###
rm -f ackinstall
rm -f Plus
rm -f ackinstall*
rm -f Plus*
clear
echo -e "\033[1;33mBAIXANDO, INSTALADOR \033[1;32m( PLUS/MOD )"
sleep 3s
wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/Plus > /dev/null 2>&1
echo ""
echo -e "\033[1;33mBAIXADO !"
sleep 3s
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[1;32m( PLUS/MOD )"
sleep 5s
chmod +x Plus; ./Plus
rm -f Plus*
cd /bin && rm -f menu*
clear
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
echo ""
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[1;32m( ACKINSTALL )"
sleep 5s
 ### "APT INSTALL"
echo ""
echo -e "\033[1;33mBAIXANDO, PACOTES EXTRAS \033[1;32m( HTOP + GLANCES + ETC )"
sleep 3s
apt-get install screen -y > /dev/null 2>&1
apt-get install htop -y > /dev/null 2>&1
apt-get install iptables -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install slurm -y > /dev/null 2>&1
apt-get install intel-microcode -y > /dev/null 2>&1
apt-get install haveged -y > /dev/null 2>&1
apt-get install ethtool -y > /dev/null 2>&1
apt-get install net-tools -y > /dev/null 2>&1
apt-get install python3.7 -y > /dev/null 2>&1
apt-get install gcc -y > /dev/null 2>&1
apt-get install build-essential -y > /dev/null 2>&1
apt-get install sysstat -y > /dev/null 2>&1
apt-get install speedtest-cli -y > /dev/null 2>&1
apt-get install nethogs -y > /dev/null 2>&1
apt-get remove apache -y > /dev/null 2>&1
apt-get remove rpcbind -y > /dev/null 2>&1
apt-get remove unscd -y > /dev/null 2>&1
apt-get remove irqbalance -y > /dev/null 2>&1
apt-get autoremove -y > /dev/null 2>&1
pip install glances > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
### "HORARIO DE SAO PAULO" ###
echo ""
echo -e "\033[1;33mDEFININDO, HORARIO DO SISTEMA \033[1;32m( SÃO PAULO )"
sleep 3s
echo -e "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'
### "SWAPPING" ###
echo ""
echo -e "\033[1;33mCRIANDO MEMORIA SWAP \033[1;32m( 4 GB )"
sleep 3s
fallocate -l 4G /swapfile > /dev/null 2>&1
chmod 600 /swapfile
mkswap /swapfile > /dev/null 2>&1
swapon /swapfile > /dev/null 2>&1
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "FERRAMENTAS" ###
echo ""
echo -e "\033[1;33mBAIXANDO FERRAMENTAS \033[1;32m ( TUNING + SWAP MEMORY ETC ) "
sleep 3s
cd /bin && rm -f swapmemory*
cd /bin && rm -f mtuning*
cd /bin && rm -f atualizar*
cd /bin && rm -f acksyshttpack*
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/mtuning > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/swapmemory > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/atualizar > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/acksyshttpack > /dev/null 2>&1
cd /bin && chmod +x swapmemory
cd /bin && chmod +x mtuning
cd /bin && chmod +x atualizar
cd /bin && chmod +x acksyshttpack
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
echo ""
echo -e "\033[1;33mBAIXANDO PYTHON SOCKS \033[1;32m( WSOCKS + OPEN.PY )"
sleep 3s
### "PYTHON SOCKS" ###
rm -rf /etc/SSHPlus*
mkdir /etc/SSHPlus
cd /etc/SSHPlus && rm -rf proxy.py*
cd /etc/SSHPlus && rm -rf open.py*
cd /etc/SSHPlus && rm -rf wsproxy.py*
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/SSHPlus/proxy.py > /dev/null 2>&1
cd /etc/SSHPlus && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/SSHPlus/open.py > /dev/null 2>&1
cd /etc/SSHPlus && chmod +x proxy.py
cd /etc/SSHPlus && chmod +x open.py
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "BADVPN UDP" ###
echo ""
echo -e "\033[1;33mBAIXANDO BADVPN-UDP \033[1;32m( BADVPN + BADVPN-UDPGW )"
sleep 3s
cd /bin && rm -f badvpn*
cd /bin && rm -f badvpn-udpgw*
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/badvpn > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/badvpn-udpgw > /dev/null 2>&1
cd /bin && chmod +x badvpn
cd /bin && chmod +x badvpn-udpgw
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "BOTSSH" ###
echo ""
echo -e "\033[1;33mBAIXANDO BOTSSH \033[1;32m( BOT TELEGRAM )"
sleep 3s
cd /bin && rm -f botssh
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/botssh > /dev/null 2>&1
cd /bin && chmod +x botssh
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "SLOW-DNS" ###
echo ""
echo -e "\033[1;33mBAIXANDO SLOW DNS \033[1;32m( SLOWDNS MANAGER )"
sleep 3s
rm -rf /etc/slowdns*
mkdir /etc/slowdns
rm -f /bin/slowdns*
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/dns-server > /dev/null  2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/remove-slow > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/restartdns > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns-drop > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns-info > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns-socks > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns-ssh > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/slowdns-ssl > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/startdns > /dev/null 2>&1
cd /etc/slowdns && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/etc/slowdns/stopdns > /dev/null 2>&1
cd /etc/slowdns && chmod +x slowdns
cd /etc/slowdns && chmod +x dns-server
cd /etc/slowdns && chmod +x remove-slow
cd /etc/slowdns && chmod +x restartdns
cd /etc/slowdns && chmod +x slowdns-drop
cd /etc/slowdns && chmod +x slowdns-info
cd /etc/slowdns && chmod +x slowdns-socks
cd /etc/slowdns && chmod +x slowdns-ssh
cd /etc/slowdns && chmod +x slowdns-ssl
cd /etc/slowdns && chmod +x startdns
cd /etc/slowdns && chmod +x stopdns
#'+++++++++++++++++++++++++++++++++++++++++++'#
# prestessHTTP SERVER +++++ prestessHTTP SERVER +++++++'
#'+++++++++++++++++++++++++++++++++++++++++++'#
### "MENU, CONEXAO, ETC" ###
echo ""
echo -e "\033[1;33mBAIXANDO LISTA \033[1;32m(MENU + CONEXAO + ETC)"
sleep 3s
cd /bin && rm -f conexao*
cd /bin && rm -f menu*
cd /bin && rm -f sshmonitor*
cd /bin && rm -f criarusuario*
cd /bin && rm -f uexpired*
cd /bin && rm -f remover*
cd /bin && rm -f criarteste*
cd /bin && rm -f alterarlimite*
cd /bin && rm -f alterarsenha*
cd /bin && rm -f detalhes*
cd /bin && rm -f infousers*
cd /bin && rm -f expcleaner*
cd /bin && rm -f banner*
cd /bin && rm -f mudardata*
cd /bin && rm -f delscript*
cd /bin && rm -f senharoot*
cd /bin && rm -f ovpn18*
cd /bin && rm -f v2raymanager*
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/conexao > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/menu > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/sshmonitor > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/criarusuario > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/uexpired > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/remover > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/criarteste > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/alterarlimite > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/alterarsenha > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/detalhes > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/infousers > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/expcleaner > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/banner > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/mudardata > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/delscript > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/senharoot > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/ovpn18 > /dev/null 2>&1
cd /bin && wget https://raw.githubusercontent.com/prestess/HTTP/main/ackinstall-raiz/bin/v2raymanager > /dev/null 2>&1
cd /bin && chmod +x conexao
cd /bin && chmod +x menu
cd /bin && chmod +x sshmonitor
cd /bin && chmod +x criarusuario
cd /bin && chmod +x uexpired
cd /bin && chmod +x remover
cd /bin && chmod +x criarteste
cd /bin && chmod +x alterarlimite
cd /bin && chmod +x alterarsenha
cd /bin && chmod +x detalhes
cd /bin && chmod +x infousers
cd /bin && chmod +x expcleaner
cd /bin && chmod +x banner
cd /bin && chmod +x mudardata
cd /bin && chmod +x delscript
cd /bin && chmod +x senharoot
cd /bin && chmod +x ovpn18
cd /bin && chmod +x v2raymanager
#######################################
#### "FIM" ####
clear
echo -e "\033[0;34m------------------------------------"
echo -e " \033[1;32m[ INSTALAÇÃO CONCLUIDA! ] \033[1;33m"
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;33mREPOSITORIO, OFICIAL NO GITHUB"
echo -e "\033[1;32mhttps://github.com/prestessHTTP/prestessHTTP-SERVER-MANAGER "
echo -e "\033[0;34m------------------------------------"
echo -e "\033[1;33m PARA INICIAR O SCRIPT, DIGITE ( menu ) \033[0m"
echo ""
echo -e "\033[1;33m ACOMPANHE NOVIDADES NO CANAL OFICIAL 
( TELEGRAM ) \033[0m"
echo -e "\033[1;32mhttps://t.me/GodOfSkyBra"
echo ""
echo -e "\033[1;33m PARA RELATAR BUGS, OU DÚVIDAS, CONTATE-ME ! 
( TELEGRAM ) \033[0m"
echo -e "\033[1;32mhttps://t.me/Godyskyup"
echo -e "\033[0;34m------------------------------------\033[1;37m"
echo "" 
echo ""
